[build]
  builder = "dockerfile"

[deploy]
  startCommand = "node apps/studio/server.js"
  healthcheckPath = "/api/profile"
  healthcheckTimeout = 10
  restartPolicyType = "on-failure"

[docker]
  dockerfile = "apps/studio/Dockerfile"
  buildContext = "."
